### ISSUE TITLE
`this` not created when describe uses `() =>` syntax instead of `function ()` syntax

### ISSUE THREAD

**Issue by snowe2010** [gradecam/jasmine-co#9]
Like the title says, 

```
describe("Applying", async () => {

  const jasmineCo = require('jasmine-co');
  jasmineCo.install();

  beforeEach(async () => {
    this;  //undefined
```

notice that `this` is undefined.
Changing the `describe` to use a `function` instead results in `this` populating properly

```
describe("Applying", function () {

  const jasmineCo = require('jasmine-co');
  jasmineCo.install();

  beforeEach(async () => {
    this;  //defined
```

**Comment by putermancer** [comment]
That's a language feature, not a limitation of jasmine-co. Using arrow functions preserves lexical this--whatever it was in the scope where you declare the arrow function, rather than what would normally be used for the functions invocation. Using standard function declarations is the correct solution to this, as it does not change the behavior of this. 

The pattern I generally follow is to use arrow functions for describe, since the this object doesn't matter / isn't used directly in describe blocks, and then use standard function declarations for before / after / it blocks, allowing the jasmine context object to successfully be provided as the this object.

**Comment by snowe2010** [comment]
Ah, ok thank you. Could the README be modified to point this out? For newbies like me?

**Comment by snowe2010** [comment]
How does the lexical this work across nested describes? 

```
describe("When a user has ", function () {
  beforeAll(async function() {
    this.iam = await helpers.iam.localToken(headers);
    this.onlineSales = await helpers.onlineSales.onlineSalesStart(headers);
  });

  describe("incomes", () => {
    this.income = helpers.income.createIncome(headers, this.onlineSales.applicantId);
```
is not working. Nor is switching out any of the `function()` for `()=>` or async version etc.
